/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'id' : bigint,
  'activityType' : string,
  'summary' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface Chat {
  'id' : bigint,
  'title' : string,
  'messages' : Array<Message>,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'pinned' : boolean,
  'folder' : [] | [bigint],
}
export interface DocumentRecord {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'fileType' : string,
  'updatedAt' : bigint,
}
export interface Folder { 'id' : bigint, 'name' : string, 'createdAt' : bigint }
export interface Message {
  'model' : [] | [Model],
  'content' : string,
  'mode' : [] | [Mode],
  'role' : Role,
  'timestamp' : bigint,
}
export type Mode = { 'normal' : null } |
  { 'research' : null } |
  { 'codingAssistant' : null } |
  { 'documentAssistant' : null } |
  { 'imageAnalysis' : null } |
  { 'internetSearch' : null } |
  { 'youtubeSearch' : null } |
  { 'emailAssistant' : null } |
  { 'knowledgeBase' : null };
export type Model = { 'gpt' : null } |
  { 'claude' : null } |
  { 'mistral' : null } |
  { 'qwen' : null } |
  { 'llama' : null } |
  { 'gemini' : null } |
  { 'ollama' : null } |
  { 'deepseek' : null };
export type Role = { 'systemMsg' : null } |
  { 'user' : null } |
  { 'assistant' : null };
export interface SearchRecord {
  'id' : bigint,
  'queryText' : string,
  'timestamp' : bigint,
  'resultCount' : bigint,
}
export type SessionId = string;
export interface ToolUsage {
  'id' : bigint,
  'inputSummary' : string,
  'outputSummary' : string,
  'timestamp' : bigint,
  'toolName' : string,
}
export interface _SERVICE {
  '__activity' : ActorMethod<
    [[] | [SessionId], [] | [bigint]],
    Array<[SessionId, Array<ActivityEntry>]>
  >,
  '__chats' : ActorMethod<
    [[] | [SessionId], [] | [bigint]],
    Array<[SessionId, Array<Chat>]>
  >,
  '__documents' : ActorMethod<
    [[] | [SessionId], [] | [bigint]],
    Array<[SessionId, Array<DocumentRecord>]>
  >,
  '__folders' : ActorMethod<
    [[] | [SessionId], [] | [bigint]],
    Array<[SessionId, Array<Folder>]>
  >,
  '__nextActivityId' : ActorMethod<[], any>,
  '__nextChatId' : ActorMethod<[], any>,
  '__nextDocumentId' : ActorMethod<[], any>,
  '__nextFolderId' : ActorMethod<[], any>,
  '__nextSearchId' : ActorMethod<[], any>,
  '__nextToolUsageId' : ActorMethod<[], any>,
  '__searchHistory' : ActorMethod<
    [[] | [SessionId], [] | [bigint]],
    Array<[SessionId, Array<SearchRecord>]>
  >,
  '__toolUsage' : ActorMethod<
    [[] | [SessionId], [] | [bigint]],
    Array<[SessionId, Array<ToolUsage>]>
  >,
  'addMessage' : ActorMethod<[SessionId, bigint, Message], [] | [Chat]>,
  /**
   * / Per-session tool-usage records, keyed by anonymous session id.
   */
  'clearActivity' : ActorMethod<[SessionId], boolean>,
  'createChat' : ActorMethod<[SessionId, string], Chat>,
  'createDocument' : ActorMethod<[SessionId, string, string], DocumentRecord>,
  'createFolder' : ActorMethod<[SessionId, string], Folder>,
  'deleteChat' : ActorMethod<[SessionId, bigint], boolean>,
  /**
   * / Global next-activity-id counter (monotonic across all sessions).
   */
  'deleteDocument' : ActorMethod<[SessionId, bigint], boolean>,
  'deleteFolder' : ActorMethod<[SessionId, bigint], boolean>,
  'getChat' : ActorMethod<[SessionId, bigint], [] | [Chat]>,
  'getDocument' : ActorMethod<[SessionId, bigint], [] | [DocumentRecord]>,
  /**
   * / Per-session activity log, keyed by anonymous session id.
   */
  'listActivity' : ActorMethod<[SessionId], Array<ActivityEntry>>,
  'listChats' : ActorMethod<[SessionId], Array<Chat>>,
  'listDocuments' : ActorMethod<[SessionId], Array<DocumentRecord>>,
  'listFolders' : ActorMethod<[SessionId], Array<Folder>>,
  /**
   * / Per-session activity log, keyed by anonymous session id.
   */
  'listSearchHistory' : ActorMethod<[SessionId], Array<SearchRecord>>,
  /**
   * / Per-session activity log, keyed by anonymous session id.
   */
  'listToolUsage' : ActorMethod<[SessionId], Array<ToolUsage>>,
  'logActivity' : ActorMethod<
    [SessionId, string, string, string],
    ActivityEntry
  >,
  'logSearch' : ActorMethod<[SessionId, string, bigint], SearchRecord>,
  'logToolUsage' : ActorMethod<[SessionId, string, string, string], ToolUsage>,
  'renameFolder' : ActorMethod<[SessionId, bigint, string], [] | [Folder]>,
  /**
   * / Global next-folder-id counter (monotonic across all sessions).
   */
  'updateChat' : ActorMethod<
    [SessionId, bigint, [] | [string], [] | [[] | [bigint]], [] | [boolean]],
    [] | [Chat]
  >,
  /**
   * / Per-session activity log, keyed by anonymous session id.
   */
  'updateDocument' : ActorMethod<
    [SessionId, bigint, string, string],
    [] | [DocumentRecord]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];