/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Model = IDL.Variant({
  'gpt' : IDL.Null,
  'claude' : IDL.Null,
  'mistral' : IDL.Null,
  'qwen' : IDL.Null,
  'llama' : IDL.Null,
  'gemini' : IDL.Null,
  'ollama' : IDL.Null,
  'deepseek' : IDL.Null,
});
export const Mode = IDL.Variant({
  'normal' : IDL.Null,
  'research' : IDL.Null,
  'codingAssistant' : IDL.Null,
  'documentAssistant' : IDL.Null,
  'imageAnalysis' : IDL.Null,
  'internetSearch' : IDL.Null,
  'youtubeSearch' : IDL.Null,
  'emailAssistant' : IDL.Null,
  'knowledgeBase' : IDL.Null,
});
export const Role = IDL.Variant({
  'systemMsg' : IDL.Null,
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Message = IDL.Record({
  'model' : IDL.Opt(Model),
  'content' : IDL.Text,
  'mode' : IDL.Opt(Mode),
  'role' : Role,
  'timestamp' : IDL.Int,
});
export const Chat = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'pinned' : IDL.Bool,
  'folder' : IDL.Opt(IDL.Nat),
});
export const Folder = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '__chats' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Chat)))],
      ['query'],
    ),
  '__folders' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Folder)))],
      ['query'],
    ),
  '__nextChatId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextFolderId' : IDL.Func([], [IDL.Reserved], ['query']),
  'addMessage' : IDL.Func([IDL.Nat, Message], [IDL.Opt(Chat)], []),
  'createChat' : IDL.Func([IDL.Text], [Chat], []),
  'createFolder' : IDL.Func([IDL.Text], [Folder], []),
  'deleteChat' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFolder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getChat' : IDL.Func([IDL.Nat], [IDL.Opt(Chat)], []),
  'listChats' : IDL.Func([], [IDL.Vec(Chat)], []),
  'listFolders' : IDL.Func([], [IDL.Vec(Folder)], []),
  'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Folder)], []),
  'updateChat' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Opt(IDL.Nat)),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Opt(Chat)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Model = IDL.Variant({
    'gpt' : IDL.Null,
    'claude' : IDL.Null,
    'mistral' : IDL.Null,
    'qwen' : IDL.Null,
    'llama' : IDL.Null,
    'gemini' : IDL.Null,
    'ollama' : IDL.Null,
    'deepseek' : IDL.Null,
  });
  const Mode = IDL.Variant({
    'normal' : IDL.Null,
    'research' : IDL.Null,
    'codingAssistant' : IDL.Null,
    'documentAssistant' : IDL.Null,
    'imageAnalysis' : IDL.Null,
    'internetSearch' : IDL.Null,
    'youtubeSearch' : IDL.Null,
    'emailAssistant' : IDL.Null,
    'knowledgeBase' : IDL.Null,
  });
  const Role = IDL.Variant({
    'systemMsg' : IDL.Null,
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Message = IDL.Record({
    'model' : IDL.Opt(Model),
    'content' : IDL.Text,
    'mode' : IDL.Opt(Mode),
    'role' : Role,
    'timestamp' : IDL.Int,
  });
  const Chat = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'pinned' : IDL.Bool,
    'folder' : IDL.Opt(IDL.Nat),
  });
  const Folder = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    '__chats' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Chat)))],
        ['query'],
      ),
    '__folders' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Folder)))],
        ['query'],
      ),
    '__nextChatId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextFolderId' : IDL.Func([], [IDL.Reserved], ['query']),
    'addMessage' : IDL.Func([IDL.Nat, Message], [IDL.Opt(Chat)], []),
    'createChat' : IDL.Func([IDL.Text], [Chat], []),
    'createFolder' : IDL.Func([IDL.Text], [Folder], []),
    'deleteChat' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFolder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getChat' : IDL.Func([IDL.Nat], [IDL.Opt(Chat)], []),
    'listChats' : IDL.Func([], [IDL.Vec(Chat)], []),
    'listFolders' : IDL.Func([], [IDL.Vec(Folder)], []),
    'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Folder)], []),
    'updateChat' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Opt(IDL.Nat)),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Opt(Chat)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };