/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chat {
  'id' : bigint,
  'title' : string,
  'messages' : Array<Message>,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'pinned' : boolean,
  'folder' : [] | [bigint],
}
export interface Folder { 'id' : bigint, 'name' : string, 'createdAt' : bigint }
export interface Message {
  'model' : [] | [Model],
  'content' : string,
  'mode' : [] | [Mode],
  'role' : Role,
  'timestamp' : bigint,
}
export type Mode = { 'normal' : null } |
  { 'research' : null } |
  { 'codingAssistant' : null } |
  { 'documentAssistant' : null } |
  { 'imageAnalysis' : null } |
  { 'internetSearch' : null } |
  { 'youtubeSearch' : null } |
  { 'emailAssistant' : null } |
  { 'knowledgeBase' : null };
export type Model = { 'gpt' : null } |
  { 'claude' : null } |
  { 'mistral' : null } |
  { 'qwen' : null } |
  { 'llama' : null } |
  { 'gemini' : null } |
  { 'ollama' : null } |
  { 'deepseek' : null };
export type Role = { 'systemMsg' : null } |
  { 'user' : null } |
  { 'assistant' : null };
export interface _SERVICE {
  '__chats' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, Array<Chat>]>
  >,
  '__folders' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, Array<Folder>]>
  >,
  '__nextChatId' : ActorMethod<[], any>,
  '__nextFolderId' : ActorMethod<[], any>,
  'addMessage' : ActorMethod<[bigint, Message], [] | [Chat]>,
  'createChat' : ActorMethod<[string], Chat>,
  'createFolder' : ActorMethod<[string], Folder>,
  'deleteChat' : ActorMethod<[bigint], boolean>,
  'deleteFolder' : ActorMethod<[bigint], boolean>,
  'getChat' : ActorMethod<[bigint], [] | [Chat]>,
  'listChats' : ActorMethod<[], Array<Chat>>,
  'listFolders' : ActorMethod<[], Array<Folder>>,
  'renameFolder' : ActorMethod<[bigint, string], [] | [Folder]>,
  'updateChat' : ActorMethod<
    [bigint, [] | [string], [] | [[] | [bigint]], [] | [boolean]],
    [] | [Chat]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];