/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Message {
    model?: Model;
    content: string;
    mode?: Mode;
    role: Role;
    timestamp: bigint;
}
export interface Folder {
    id: bigint;
    name: string;
    createdAt: bigint;
}
export interface Chat {
    id: bigint;
    title: string;
    messages: Array<Message>;
    createdAt: bigint;
    updatedAt: bigint;
    pinned: boolean;
    folder?: bigint;
}
export enum Mode {
    normal = "normal",
    research = "research",
    codingAssistant = "codingAssistant",
    documentAssistant = "documentAssistant",
    imageAnalysis = "imageAnalysis",
    internetSearch = "internetSearch",
    youtubeSearch = "youtubeSearch",
    emailAssistant = "emailAssistant",
    knowledgeBase = "knowledgeBase"
}
export enum Model {
    gpt = "gpt",
    claude = "claude",
    mistral = "mistral",
    qwen = "qwen",
    llama = "llama",
    gemini = "gemini",
    ollama = "ollama",
    deepseek = "deepseek"
}
export enum Role {
    systemMsg = "systemMsg",
    user = "user",
    assistant = "assistant"
}
export interface backendInterface {
    __chats(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, Array<Chat>]>>;
    __folders(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, Array<Folder>]>>;
    __nextChatId(): Promise<any>;
    __nextFolderId(): Promise<any>;
    addMessage(chatId: bigint, message: Message): Promise<Chat | null>;
    createChat(title: string): Promise<Chat>;
    createFolder(name: string): Promise<Folder>;
    deleteChat(id: bigint): Promise<boolean>;
    deleteFolder(id: bigint): Promise<boolean>;
    getChat(id: bigint): Promise<Chat | null>;
    listChats(): Promise<Array<Chat>>;
    listFolders(): Promise<Array<Folder>>;
    renameFolder(id: bigint, name: string): Promise<Folder | null>;
    updateChat(id: bigint, title: string | null, folder: Some<bigint | null> | None, pinned: boolean | null): Promise<Chat | null>;
}
import type { Chat as _Chat, Folder as _Folder, Message as _Message, Mode as _Mode, Model as _Model, Role as _Role } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __chats(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, Array<Chat>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__chats(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__chats(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __folders(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, Array<Folder>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__folders(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__folders(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __nextChatId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextChatId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextChatId();
            return result;
        }
    }
    async __nextFolderId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextFolderId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextFolderId();
            return result;
        }
    }
    async addMessage(arg0: bigint, arg1: Message): Promise<Chat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, to_candid_Message_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, to_candid_Message_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async createChat(arg0: string): Promise<Chat> {
        if (this.processError) {
            try {
                const result = await this.actor.createChat(arg0);
                return from_candid_Chat_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChat(arg0);
            return from_candid_Chat_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFolder(arg0: string): Promise<Folder> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0);
            return result;
        }
    }
    async deleteChat(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChat(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async getChat(arg0: bigint): Promise<Chat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChat(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChat(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listChats(): Promise<Array<Chat>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChats();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChats();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFolders(): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFolders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFolders();
            return result;
        }
    }
    async renameFolder(arg0: bigint, arg1: string): Promise<Folder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameFolder(arg0, arg1);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameFolder(arg0, arg1);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateChat(arg0: bigint, arg1: string | null, arg2: Some<bigint | null> | None, arg3: boolean | null): Promise<Chat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChat(arg0, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChat(arg0, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Chat_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chat): Chat {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Mode_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mode): Mode {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Model_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Model): Model {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Model]): Model | null {
    return value.length === 0 ? null : from_candid_Model_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mode]): Mode | null {
    return value.length === 0 ? null : from_candid_Mode_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chat]): Chat | null {
    return value.length === 0 ? null : from_candid_Chat_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Folder]): Folder | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: [] | [_Model];
    content: string;
    mode: [] | [_Mode];
    role: _Role;
    timestamp: bigint;
}): {
    model?: Model;
    content: string;
    mode?: Mode;
    role: Role;
    timestamp: bigint;
} {
    return {
        model: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.model)),
        content: value.content,
        mode: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.mode)),
        role: from_candid_Role_n17(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    messages: Array<_Message>;
    createdAt: bigint;
    updatedAt: bigint;
    pinned: boolean;
    folder: [] | [bigint];
}): {
    id: bigint;
    title: string;
    messages: Array<Message>;
    createdAt: bigint;
    updatedAt: bigint;
    pinned: boolean;
    folder?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        messages: from_candid_vec_n8(_uploadFile, _downloadFile, value.messages),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        pinned: value.pinned,
        folder: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.folder))
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_Chat>]): [Principal, Array<Chat>] {
    return [
        value[0],
        from_candid_vec_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gpt: null;
} | {
    claude: null;
} | {
    mistral: null;
} | {
    qwen: null;
} | {
    llama: null;
} | {
    gemini: null;
} | {
    ollama: null;
} | {
    deepseek: null;
}): Model {
    return "gpt" in value ? Model.gpt : "claude" in value ? Model.claude : "mistral" in value ? Model.mistral : "qwen" in value ? Model.qwen : "llama" in value ? Model.llama : "gemini" in value ? Model.gemini : "ollama" in value ? Model.ollama : "deepseek" in value ? Model.deepseek : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    research: null;
} | {
    codingAssistant: null;
} | {
    documentAssistant: null;
} | {
    imageAnalysis: null;
} | {
    internetSearch: null;
} | {
    youtubeSearch: null;
} | {
    emailAssistant: null;
} | {
    knowledgeBase: null;
}): Mode {
    return "normal" in value ? Mode.normal : "research" in value ? Mode.research : "codingAssistant" in value ? Mode.codingAssistant : "documentAssistant" in value ? Mode.documentAssistant : "imageAnalysis" in value ? Mode.imageAnalysis : "internetSearch" in value ? Mode.internetSearch : "youtubeSearch" in value ? Mode.youtubeSearch : "emailAssistant" in value ? Mode.emailAssistant : "knowledgeBase" in value ? Mode.knowledgeBase : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    systemMsg: null;
} | {
    user: null;
} | {
    assistant: null;
}): Role {
    return "systemMsg" in value ? Role.systemMsg : "user" in value ? Role.user : "assistant" in value ? Role.assistant : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_Chat>]>): Array<[Principal, Array<Chat>]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chat>): Array<Chat> {
    return value.map((x)=>from_candid_Chat_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Message_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Mode_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): _Mode {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Model_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): _Model {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Some<bigint | null> | None): [] | [[] | [bigint]] {
    return isNone(value) ? candid_none() : candid_some(to_candid_opt_n2(_uploadFile, _downloadFile, unwrap(value)));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model?: Model;
    content: string;
    mode?: Mode;
    role: Role;
    timestamp: bigint;
}): {
    model: [] | [_Model];
    content: string;
    mode: [] | [_Mode];
    role: _Role;
    timestamp: bigint;
} {
    return {
        model: value.model ? candid_some(to_candid_Model_n22(_uploadFile, _downloadFile, value.model)) : candid_none(),
        content: value.content,
        mode: value.mode ? candid_some(to_candid_Mode_n24(_uploadFile, _downloadFile, value.mode)) : candid_none(),
        role: to_candid_Role_n26(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): {
    gpt: null;
} | {
    claude: null;
} | {
    mistral: null;
} | {
    qwen: null;
} | {
    llama: null;
} | {
    gemini: null;
} | {
    ollama: null;
} | {
    deepseek: null;
} {
    return value == Model.gpt ? {
        gpt: null
    } : value == Model.claude ? {
        claude: null
    } : value == Model.mistral ? {
        mistral: null
    } : value == Model.qwen ? {
        qwen: null
    } : value == Model.llama ? {
        llama: null
    } : value == Model.gemini ? {
        gemini: null
    } : value == Model.ollama ? {
        ollama: null
    } : value == Model.deepseek ? {
        deepseek: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): {
    normal: null;
} | {
    research: null;
} | {
    codingAssistant: null;
} | {
    documentAssistant: null;
} | {
    imageAnalysis: null;
} | {
    internetSearch: null;
} | {
    youtubeSearch: null;
} | {
    emailAssistant: null;
} | {
    knowledgeBase: null;
} {
    return value == Mode.normal ? {
        normal: null
    } : value == Mode.research ? {
        research: null
    } : value == Mode.codingAssistant ? {
        codingAssistant: null
    } : value == Mode.documentAssistant ? {
        documentAssistant: null
    } : value == Mode.imageAnalysis ? {
        imageAnalysis: null
    } : value == Mode.internetSearch ? {
        internetSearch: null
    } : value == Mode.youtubeSearch ? {
        youtubeSearch: null
    } : value == Mode.emailAssistant ? {
        emailAssistant: null
    } : value == Mode.knowledgeBase ? {
        knowledgeBase: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    systemMsg: null;
} | {
    user: null;
} | {
    assistant: null;
} {
    return value == Role.systemMsg ? {
        systemMsg: null
    } : value == Role.user ? {
        user: null
    } : value == Role.assistant ? {
        assistant: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
